// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_XLeNJGoIFluutNZB5qb8O428g6Y2zQ',
    appId: '1:502732880730:web:67ea65311d0bfb42bf9163',
    messagingSenderId: '502732880730',
    projectId: 'flutter-social-media-app-7aac7',
    authDomain: 'flutter-social-media-app-7aac7.firebaseapp.com',
    storageBucket: 'flutter-social-media-app-7aac7.appspot.com',
    measurementId: 'G-E3K8FBTRG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP-m14DVZIRfCzvTn1l6BoHsJ7kV6bBUE',
    appId: '1:502732880730:android:3c8ed213362cc09bbf9163',
    messagingSenderId: '502732880730',
    projectId: 'flutter-social-media-app-7aac7',
    storageBucket: 'flutter-social-media-app-7aac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOT4480Rs9FSviB3iVMnoAiA9zDSCzMiE',
    appId: '1:502732880730:ios:69cb1355e97fc7d9bf9163',
    messagingSenderId: '502732880730',
    projectId: 'flutter-social-media-app-7aac7',
    storageBucket: 'flutter-social-media-app-7aac7.appspot.com',
    iosClientId: '502732880730-j4msnqaur1oe4dc8m2df87gomitaupdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOT4480Rs9FSviB3iVMnoAiA9zDSCzMiE',
    appId: '1:502732880730:ios:69cb1355e97fc7d9bf9163',
    messagingSenderId: '502732880730',
    projectId: 'flutter-social-media-app-7aac7',
    storageBucket: 'flutter-social-media-app-7aac7.appspot.com',
    iosClientId: '502732880730-j4msnqaur1oe4dc8m2df87gomitaupdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
